spring.application.name=contract-management

spring.mongodb.uri=mongodb://localhost:27017/contract_db

jwt.secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB